apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app4
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kustomize-app4
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sync-waves
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
